version: "3.7"
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=smartlink
      - MYSQL_ROOT_PASSWORD=1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backend_network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: ./apidocs.json

  server:
    restart: always
    build:
      context: .
    environment:
      - DB_HOSTNAME=database
      - DB_NAME=smartlink
      - DB_USERNAME=root
      - DB_PASSWORD=1
      - JWT_SECRET=smartlink
      - JWT_SECRET_REFRESH=refreshtoken!2
      - JWT_ACCESS_TOKEN_EXPIRED=5m
      - JWT_REFRESH_TOKEN_EXPIRED=1d
    command:
      - /bin/sh
      - -c
      - |
        npx sequelize db:migrate:undo:all
        npx sequelize db:migrate
        npm start
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - backend_network
networks:
  backend_network:
    name: backend_network
